### ISSUE TITLE
Romania validation error - update_prevalence.py

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1448]
**Describe the bug**
Running `update_prevalence.py` results in an error while parsing data from Romania.  

**Link to microCOVID scenario**
N/A

**To Reproduce**
1. Set up your micrCOVID developer environment per the 'Local Development' section of `README.md`
2. Run `./update_prevalence.py`
3. See this error:

```
[...]
a29b7e58e7d073... read 3223 objects
ignoring unknown county fips 69100
ignoring unknown county fips 69110
ignoring unknown county fips 69120
Fetching https://api.covidactnow.org/v2/states.json?apiKey=9c52c57d858b4aa0bba29b7e58e7d073... read 53 objects
Fetching https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/testing/covid-testing-all-observations.csv... read 101894 objects
Fetching https://covid19.geo-spatial.org/external/charts_vasile/assets/json/cazuri_zile_long.json... Traceback (most recent call last):
  File "./update_prevalence.py", line 1604, in <module>
    main()
  File "./update_prevalence.py", line 1500, in main
    parse_romania_prevalence_data(cache, data)
  File "./update_prevalence.py", line 1307, in parse_romania_prevalence_data
    for line in parse_json_list(cache, RomaniaPrevalenceData, RomaniaPrevalenceData.SOURCE):
  File "./update_prevalence.py", line 1106, in parse_json_list
    result = pydantic.parse_obj_as(List[model], json.loads(cache.get(url)))
  File "/Users/broz/src/microCOVID/.venv/lib/python3.8/site-packages/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/Users/broz/src/microCOVID/.venv/lib/python3.8/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List[__main__.RomaniaPrevalenceData]]
__root__ -> 32718 -> Data
  invalid date format (type=value_error.date)
$
```

**Expected behavior**
Romanian data parsed, included in `location.ts` as well as spreadsheet .csv files.

**Is this a regression?**
Yes; worked when I ran it to generate https://github.com/microCOVID/microCOVID/pull/1444/commits/4109c430d85cbf9b8ec187f0bedf55bad5ff2d06

**Additional context / screenshots**
This is on top of the existing Canada data failure.  https://github.com/microCOVID/microCOVID/issues/1441 suggests a method to keep these failures from holding back critical data updates for the rest of the world; I'd love to get feedback.

**Comment by apiology** [comment]
This seems to have been temporary, and #1450 is now in place to not block other updates if it happens again.
