### ISSUE TITLE
Prevalence is stale

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1476]
The prevalence warning popped up today:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3681194/174490002-3334e692-9f8d-4eed-b929-1941c60d5dfa.png">

This appears to be the last update PR that was opened: https://github.com/microCOVID/microCOVID/pull/1475

**Comment by apiology** [comment]
@beshaya: Heads-up on this one.  It's possible that I'll be able to dig in on this one this weekend, but I have not had time yet.

**Comment by apiology** [comment]
```sh
$ ./update_prevalence.py 
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv... read 4318 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-24-2022.csv... read 4012 objects
[...]
Discarding State(fullname='Presov, Slovakia', name='Presov', population=798596, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), country='Slovakia', fips=None, counties={}) with no case data
Discarding State(fullname='Trencin, Slovakia', name='Trencin', population=600386, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), country='Slovakia', fips=None, counties={}) with no case data
Discarding State(fullname='Trnava, Slovakia', name='Trnava', population=554172, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), country='Slovakia', fips=None, counties={}) with no case data
Discarding State(fullname='Zilina, Slovakia', name='Zilina', population=694763, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), country='Slovakia', fips=None, counties={}) with no case data
Positive test rate for New Zealand is 1.5345431391276663
Warning: Endpoints say no new cases and max(values) says new cases; check numbers manually for Amazonas, Peru. 1 negative cumulative case corrections [3], values=[44253, 44253, 44253, 44253, 44241, 44241, 44241, 44241], discrepancy 12
Warning: Endpoints say no new cases and max(values) says new cases; check numbers manually for Huancavelica, Peru. 1 negative cumulative case corrections [3], values=[25875, 25875, 25875, 25875, 25873, 25873, 25873, 25873], discrepancy 2
Traceback (most recent call last):
  File "./update_prevalence.py", line 1654, in <module>
    main()
  File "./update_prevalence.py", line 1577, in main
    app_locations[state.app_key] = state.as_app_data()
  File "./update_prevalence.py", line 674, in as_app_data
    result = super().as_app_data()
  File "./update_prevalence.py", line 609, in as_app_data
    last_week = self.cases_last_week
  File "./update_prevalence.py", line 476, in cases_last_week
    return self.cases_in_cum_cases(self.recent_daily_cumulative_cases[-8:])
  File "./update_prevalence.py", line 405, in recent_daily_cumulative_cases
    raise ValueError(f"Missing data for {self.fullname} on {current:%Y-%m-%d}")
ValueError: Missing data for Alba, Romania on 2022-06-24
$
```

**Comment by apiology** [comment]
It appears our Romania data source stopped updating:

```sh
broz@bigbookpro:~/src/microCOVID$ curl https://covid19.geo-spatial.org/external/charts_vasile/assets/json/cazuri_zile_long.json | jq | tail -50
  {
    "Data": "2022-06-12",
    "Judet": "Suceava",
    "Populatie": "622,533.0",
    "Cazuri total": 58303,
    "Cazuri noi": 4
  },
  {
    "Data": "2022-06-12",
    "Judet": "Teleorman",
    "Populatie": "328,683.0",
    "Cazuri total": 34628,
    "Cazuri noi": 0
  },
  {
    "Data": "2022-06-12",
    "Judet": "Timiș",
    "Populatie": "705,745.0",
    "Cazuri total": 153259,
    "Cazuri noi": 6
  },
  {
    "Data": "2022-06-12",
    "Judet": "Tulcea",
    "Populatie": "192,037.0",
    "Cazuri total": 20424,
    "Cazuri noi": 1
  },
  {
    "Data": "2022-06-12",
    "Judet": "Vaslui",
    "Populatie": "371,156.0",
    "Cazuri total": 37233,
    "Cazuri noi": 4
  },
  {
    "Data": "2022-06-12",
    "Judet": "Vâlcea",
    "Populatie": "348,318.0",
    "Cazuri total": 41139,
    "Cazuri noi": 3
  },
  {
    "Data": "2022-06-12",
    "Judet": "Vrancea",
    "Populatie": "317,419.0",
    "Cazuri total": 26456,
    "Cazuri noi": 0
  }
]
$ 
```

**Comment by apiology** [comment]
I sent an email to the contact address listed on the site to make sure they were aware.

**Comment by apiology** [comment]
Thanks for merging #1478, @beshaya!  

Going forward, is there any easy existing way I can get an email or some kind of alert when these prevalence runs fail in GitHub Actions?  I'm following the project but I don't see alerts--maybe folks with elevated access get more emails?  Do those Sentry alerts go somewhere you could wire me into?  I might poke around and suggest a mechanism if there's nothing existing and convenient.

**Comment by beshaya** [comment]
Hey Vince,

Shoot me an email at ***@***.*** - I'd love to get you access to
all the things.
