### ISSUE TITLE
Prevalence run failure - "ValueError: Missing data for South, Alberta, Canada on 2022-06-26"

### ISSUE THREAD

**Issue by vbrozatcalendly** [microCOVID/microCOVID#1480]
The automated prevalence run failed today:

```
[...]
Discarding State(fullname='Zilina, Slovakia', name='Zilina', population=694763, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), country='Slovakia', fips=None, counties={}) with no case data
Positive test rate for Alberta is 1.9058823529411764
Traceback (most recent call last):
  File "update_prevalence.py", line 1683, in <module>
    main()
  File "update_prevalence.py", line 1608, in main
    app_locations[county.app_key] = county.as_app_data()
  File "update_prevalence.py", line 625, in as_app_data
    last_week = self.cases_last_week
  File "update_prevalence.py", line 492, in cases_last_week
    return self.cases_in_cum_cases(self.recent_daily_cumulative_cases[-8:])
  File "update_prevalence.py", line 419, in recent_daily_cumulative_cases
    raise ValueError(
ValueError: Missing data for South, Alberta, Canada on 2022-06-26 - Counter({datetime.date(2022, 6, 20): 38244, datetime.date(2022, 6, 21): 38244, datetime.date(2022, 6, 22): 38244, datetime.date(2022, 6, 23): 38244, datetime.date(2022, 6, 24): 38244, datetime.date(2022, 6, 19): 38231, datetime.date(2022, 6, 18): 38226, datetime.date(2022, 6, 17): 38215, datetime.date(2022, 6, 16): 38201, datetime.date(2022, 6, 15): 38189, datetime.date(2022, 6, 14): 38183, datetime.date(2022, 6, 13): 38170, datetime.date(2022, 6, 12): 38162, datetime.date(2022, 6, 11): 38151, datetime.date(2022, 6, 10): 38145})
Sentry is attempting to send 99 pending error messages
```

See full logs here: https://github.com/microCOVID/microCOVID/runs/7074724224?check_suite_focus=true

**Comment by apiology** [comment]
With a little luck, this should start working with tomorrow's run--the gap in updates seems to have been resolved two hours after the scheduled prevalence run: 

* https://github.com/microCOVID/microCOVID/actions/runs/2569836417
* https://github.com/ccodwg/CovidTimelineCanada/commits/main/data/hr/cases_hr.csv

The issue in the upstream API is being addressed in https://github.com/ccodwg/Covid19CanadaAPI/issues/49
