### ISSUE TITLE
Prevalence updates failing

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1570]
**Describe the bug**

Automatic prevalence updates have started failing - the first failure started on  the `auto-update-prevalence-2022-09-17--14-21-18` branch.

**Link to microCOVID scenario**

https://github.com/microCOVID/microCOVID/actions

**To Reproduce**

1. Set up per https://github.com/microCOVID/microCOVID/#local-development
2. Run `./update_prevalence.py`
3. See error:
 
```sh
Traceback (most recent call last):
  File "./update_prevalence.py", line 1685, in <module>
    main()
  File "./update_prevalence.py", line 1608, in main
    app_locations[state.app_key] = state.as_app_data()
  File "./update_prevalence.py", line 692, in as_app_data
    result = super().as_app_data()
  File "./update_prevalence.py", line 627, in as_app_data
    last_week = self.cases_last_week
  File "./update_prevalence.py", line 494, in cases_last_week
    return self.cases_in_cum_cases(self.recent_daily_cumulative_cases[-8:])
  File "./update_prevalence.py", line 419, in recent_daily_cumulative_cases
    raise ValueError(
ValueError: Missing data for Pitcairn Islands, United Kingdom on 2022-09-18 - Counter({datetime.date(2022, 9, 13): 4, datetime.date(2022, 9, 12): 4, datetime.date(2022, 9, 11): 4, datetime.date(2022, 9, 10): 4, datetime.date(2022, 9, 9): 4, datetime.date(2022, 9, 8): 4, datetime.date(2022, 9, 7): 4, datetime.date(2022, 9, 6): 4, datetime.date(2022, 9, 5): 4, datetime.date(2022, 9, 4): 4, datetime.date(2022, 9, 3): 4, datetime.date(2022, 9, 2): 4})
```

**Expected behavior**

Prevalence updates successfully.

**Is this a regression?**

Yes; last success was 2022-09-14

**Additional context / screenshots**

<img width="865" alt="image" src="https://user-images.githubusercontent.com/3681194/191012833-cdf64b01-5103-45a7-9a2b-c71cff3daacb.png">

**Comment by apiology** [comment]
Perhaps related to this upstream issue https://github.com/CSSEGISandData/COVID-19/issues/6096

Fixed upstream in https://github.com/CSSEGISandData/COVID-19/commit/789b82db2b9e6a33ac64be8e137f1d8b68646046 - prevalence just ran successfully and the site is now up to date.
