### ISSUE TITLE
Prevalence runs failing

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1695]
It appears that prevalence runs started failing on 2022-12-13 and have continued to fail: https://github.com/microCOVID/microCOVID/actions/workflows/prevalence.yml

To reproduce this, you can set up a local development environment with the steps in the README: https://github.com/microCOVID/microCOVID/actions/workflows/prevalence.yml

Here's the relevant bit of the logs:

```
No county-level case data (19,237,682 people): from Romania due to staleness - last update was 2022-11-14
Fetching https://raw.githubusercontent.com/ccodwg/CovidTimelineCanada/main/geo/hr.csv...
read 100 objects
Fetching https://raw.githubusercontent.com/ccodwg/CovidTimelineCanada/main/geo/pt.csv...
read 14 objects
Fetching region 1: South (4831)
Fetching https://api.covid19tracker.ca/reports/regions/4831?fill_dates=true&after=2022-11-27&before=2022-12-13...
Traceback (most recent call last):
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1934, in <module>
    main()
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1831, in main
    parse_canada_prevalence_data(cache, data)
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1[70](https://github.com/microCOVID/microCOVID/actions/runs/3695555203/jobs/6258087385#step:10:71)6, in parse_canada_prevalence_data
    process_regional_vaccination_reports()
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 16[71](https://github.com/microCOVID/microCOVID/actions/runs/3695555203/jobs/6258087385#step:10:72), in process_regional_vaccination_reports
    vaccination_reports = parse_json(
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1325, in parse_json
    cache.get(url)
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1259, in get
    response.raise_for_status()
  File "/home/runner/.virtualenvs/.venv/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.covid19tracker.ca/reports/regions/4[83](https://github.com/microCOVID/microCOVID/actions/runs/3695555203/jobs/6258087385#step:10:84)1?fill_dates=true&after=2022-11-27&before=2022-12-13
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by xaqrox** [comment]
I tried running the prevalence script from a fresh install, and it succeeded! Perhaps that data source was down for a while? Can we try re-triggering the GH action?

**Comment by xaqrox** [comment]
Also, this failure shows a different error: https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290
```
Run yarn prevalence -b -c -k *** -v /home/runner/.virtualenvs/.venv
yarn run v1.22.19
$ ./scripts/prevalence_helper.sh -b -c -k *** -v /home/runner/.virtualenvs/.venv
Using a manual virtualenv directory: /home/runner/.virtualenvs/.venv
Branch will be based on the currently checked out branch
Switched to a new branch 'auto-update-prevalence-2022-12-16--14-05-42'
remote: 
remote: Create a pull request for 'auto-update-prevalence-2022-12-16--14-05-42' on GitHub by visiting:        
remote:      https://github.com/microCOVID/microCOVID/pull/new/auto-update-prevalence-2022-12-16--14-05-42        
remote: 
To https://github.com/microCOVID/microCOVID
 * [new branch]          auto-update-prevalence-2022-12-16--14-05-42 -> auto-update-prevalence-2022-12-16--14-05-42
branch 'auto-update-prevalence-2022-12-16--14-05-42' set up to track 'origin/auto-update-prevalence-2022-12-16--14-05-42'.
Created branch auto-update-prevalence-2022-12-16--14-05-42
Activating the virtualenv
Activating virtulenv: /home/runner/.virtualenvs/.venv/bin/activate
Running prevalence script
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv...
read 4322 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-15-2022.csv...
read 401[7](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:8) objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-14-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-13-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-12-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-11-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-10-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-09-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-0[8](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:9)-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-1[9](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:10)/master/csse_covid_19_data/csse_covid_19_daily_reports/12-07-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-06-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-05-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-04-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-03-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-02-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-01-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/11-30-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/11-29-2022.csv...
read 4017 objects
Fetching https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/global_data/time_series_covid19_vaccine_global.csv...
read 127688 objects
Traceback (most recent call last):
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 1929, in <module>
    main()
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line 18[10](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:11), in main
    parse_jhu_vaccines_global(cache, data)
  File "/home/runner/work/microCOVID/microCOVID/update_prevalence.py", line [14](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:15)94, in parse_jhu_vaccines_global
    raise ValueError(f"Not able to gain data from {JHUVaccinesTimeseriesGlobal.SOURCE}")
ValueError: Not able to gain data from https://raw.githubusercontent.com/govex/COVID-[19](https://github.com/microCOVID/microCOVID/actions/runs/3713766288/jobs/6296813290#step:10:20)/master/data_tables/vaccine_data/global_data/time_series_covid19_vaccine_global.csv
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by apiology** [comment]
> I tried running the prevalence script from a fresh install, and it succeeded! P  Can we try re-triggering the GH action?

Success!  Hopefully tomorrow' automated run will succeed as well.

**Comment by apiology** [comment]
It did!  https://github.com/microCOVID/microCOVID/pull/1697#event-8061923999
